feat: add analysis and removing data from df_clean
Pyame/Flight-Price-Prediction pull request #17
Opened 2023-10-26 19:59 UTC by Monikaa1909

Dodałam analizę danych i usunięcie niepotrzebnych danych, na razie tylko dla tabeli df_cleans. Jeśli jest ok to lecę dalej

2023-10-27 09:53 UTC, Pyame requested changes
1. Kod i komentarze po angolsku pls
2. `df.describe()` wyświetlić statystyki kolumny
3. To można wykorzystać żeby wyświetlić w jednym miejscu która kolumna ma ile wartości unikalnych:
```
for col in data.columns:
    if len(data[col].unique()) > 50:
        print(f'{col}: {len(data[col].unique())} unique values')
    else:
        print(f'{col}: {data[col].unique()}')
```
4. po sprawdzeniu tego można zrobić to co zrobiłaś, żeby wyświetlić która wartość pokazuje się ile razy ale tylko dla niektórych kolumn bo bez sensu robić to dla kolumny która ma od groma unikalych jak np w kolumnie 'flight'
5. można dodać też od razu do tych kolumn, gdzie jest tylko kilka wartości unikalnych dodać histogram który by pokazywał wizualizację tego

2023-10-28 00:23 UTC, Pyame commented
Dla duration i days_left też można dać histogram z analizą, i czemu do niektórych kolumn dawałaś histogramy a do innych nie? pytam z ciekawości bo jak bez powodu to bym jednak też to dodał.

2023-10-28 15:30 UTC, Monikaa1909 commented
> Dla duration i days_left też można dać histogram z analizą, i czemu do niektórych kolumn dawałaś histogramy a do innych nie? pytam z ciekawości bo jak bez powodu to bym jednak też to dodał.

Dla duration uznałam to za bezsensowne, bo taka tabela miałaby prawie 500 wierszy i mi się nawet nie chciałoby z niej czegokolwiek wyciągać, bo jest mało czytelna, a co do days_left to dodałam już.

A histogramy też dodawałam tylko do rzeczy, które mi się wydawały "interesujące" i nie wiedziałam czy warto do wszystkich ale skoro pytasz to pewnie warto, więc już dodane

2023-10-28 16:58 UTC, Pyame commented
> Dla duration uznałam to za bezsensowne, bo taka tabela miałaby prawie 500 wierszy i mi się nawet nie chciałoby z niej czegokolwiek wyciągać, bo jest mało czytelna, a co do days_left to dodałam już.
> 
Dla duration można wrzucić sam histogram i przedstawić rozkład wartości, bo ogólnie to racja że tabela byłaby bez sensu w tym przypadku, ale właśnie w takich sytuacjach warto dać ten histogram albo ogólnie wykres rozkładu wartości.

Co do reszty to zaraz popatrzę co i jak

2023-10-29 18:06 UTC, merged