feat: check if data frames have a missing values
Pyame/Flight-Price-Prediction pull request #20
Opened 2023-10-29 08:40 UTC by SiwyKot41

Sprawdziłem wszystkie data frame, to o dziwo zwróciło mi wszędzie false, nie wiem czy to ja coś źle zrobiłem, czy po prostu mamy takie super dane, że nie ma brakujących wartości

2023-10-29 09:03 UTC, wvffle requested changes
wczytuj normalnie dane

2023-10-29 09:14 UTC, SiwyKot41 commented
> wczytuj normalnie dane

Kurde ja to wczytalem sobie tymczasowo, bo mi ta sciezka zrobiona domyslnie w projekcie nie dziala

2023-10-29 15:50 UTC, Pyame commented
nie sprawdzaj osobno isna i isnull bo masz ten sam rezultat, w pandasie to jeden grzyb

2023-10-29 15:52 UTC, Pyame requested changes
niepotrzebne powtarzanie czynności

2023-10-29 18:11 UTC, Pyame commented
No i jeden standard trzymaj, albo zamieniasz
`df_business.replace('', None, inplace=True)`
albo
`df_clean.replace('', float('nan'), inplace=True)`

2023-11-11 16:14 UTC, Pyame approved these changes

2023-11-11 16:14 UTC, merged